version: '3.8'

services:
  app:
    build:
      context: .
      target: staging
    ports:
      - '8888:8888'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=staging
      - DATABASE_URL=postgresql://user:password@db:5432/stagingdb
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "bun run migrate:deploy && bun run generate && bun run start"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stagingdb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d stagingdb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
