version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '8888:8888'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/devdb
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "bun run migrate:dev && bun run generate && bun run dev"

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d devdb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
